config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :games, only: [:index, :show, :create]

  # Defines the root path route ("/")
  root "games#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
# frozen_string_literal: true

class Game < ApplicationRecord
  attribute :email, :string
  attribute :name, :string
  attribute :width, :integer
  attribute :height, :integer
  attribute :mines, :integer
  attribute :config, :integer, array: true

  validates :email, :name, :width, :height, :mines, presence: true
  validates :width, :height, :mines, numericality: { only_integer: true, greater_than: 0 }

  scope :last_ordered, -> (number) { order(created_at: :desc).limit(number) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
# frozen_string_literal: true

require 'generator'

class GamesController < ApplicationController
  def index
    @games = Game.all
  end

  def show
    @game = Game.find show_params[:id]
  end

  def home
    @games ||= Game.last_ordered(10)
  end

  def create
    @new_game = Game.new **create_params
    if @new_game.valid?
      @new_game.config = Generator.new(@new_game.width, @new_game.height, @new_game.mines).board
      @new_game.save!
      redirect_to game_path(@new_game.id)
    else
      render :home, games: home
    end
  end

  private

  def show_params
    params.require('id')
    params.permit %i[id]
  end

  def create_params
    if params[:game]
      params.require('game').permit(%i[email name width height mines])
    else
      params.permit(%i[email name width height mines])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
# frozen_string_literal: true

module GameHelper
  def reconstruct_board(game)
    # Create a 2-dimensional array of 0's
    board = Array.new(game.height) { Array.new(game.width, 0) }

    # Put 1's where the bombs are
    game.config.each { |pair| board[pair.first][pair.last] = 1 }

    board
  end
end

app/views/games/home.html.erb
<div>
  <%= form_with model: @new_game, url: games_path, method: :post, class: 'bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4' do |form| %>
    <div class="flex flex-col block text-gray-700 text-sm font-bold mb-1">
      <div class="mb-2">
        <%= form.label :email, "Email:" %>
        <%= form.text_field :email, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline' %>
        <% if @new_game&.errors&.[](:email)&.first&.length&.positive? %>
          <%= form.label :email, "Email #{@new_game.errors[:email].first}", class: 'text-red-600' %>
        <% end %>
      </div>
      <div class="mb-2">
        <%= form.label :width, "Board Width:" %>
        <%= form.number_field :width, in: 1...-1, step: 1, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline' %>
        <% if @new_game&.errors&.[](:width)&.first&.length&.positive? %>
          <%= form.label :width, "Width #{@new_game.errors[:width].first}", class: 'text-red-600' %>
        <% end %>
      </div>
      <div class="mb-2">
        <%= form.label :height, "Board Height:" %>
        <%= form.number_field :height, in: 1...-1, step: 1, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline' %>
        <% if @new_game&.errors&.[](:height)&.first&.length&.positive? %>
          <%= form.label :height, "Height #{@new_game.errors[:height].first}", class: 'text-red-600' %>
        <% end %>
      </div>
      <div class="mb-2">
        <%= form.label :name, "Board Name:" %>
        <%= form.text_field :name, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline' %>
        <% if @new_game&.errors&.[](:name)&.first&.length&.positive? %>
          <%= form.label :name, "Name #{@new_game.errors[:name].first}", class: 'text-red-600' %>
        <% end %>
      </div>
      <div class="mb-6">
        <%= form.label :mines, "Number of mines:" %>
        <%= form.number_field :mines, in: 1...-1, step: 1, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline' %>
        <% if @new_game&.errors&.[](:mines)&.first&.length&.positive? %>
          <%= form.label :mines, "Number of mines #{@new_game.errors[:mines].first}", class: 'text-red-600' %>
        <% end %>
      </div>
      <%= form.submit "Generate Board", class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline' %>
    </div>
  <% end %>

  <!--  Last 10 games -->
  <div class="flex flex-col gap-y-1 bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
    <h2 class="mb-2"><strong>Last 10 games</strong></h2>

    <%= render "shared/table", games: @games %>

    <%= link_to 'View all generated boards', games_path, class: 'underline' %>

  </div>
</div>

app/views/games/index.html.erb
<div class="flex flex-col gap-y-1 bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
  <h2 class="mb-2"><strong>All Games</strong></h2>

  <%= render "shared/table", games: @games %>
</div>

app/views/games/show.html.erb
<div class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
  <!--  Creator information-->
  <div class="flex flex-col mb-6 block text-gray-700 text-md font-bold">
    <div class="flex gap-x-1">
      <div>
        Board name:
      </div>
      <div>
        <%= @game.name %>
      </div>
    </div>

    <div class="flex gap-x-1">
      <div>
        Email:
      </div>
      <div>
        <%= @game.email %>
      </div>
    </div>
  </div>


  <%= render "shared/board", board: reconstruct_board(@game) %>
</div>

app/views/home/index.html.erb
<div>
  <%= form_with url: 'games', method: :post, class: 'bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4' do |form| %>
    <div class="flex flex-col block text-gray-700 text-sm font-bold mb-1">
      <div class="mb-2">
        <%= form.label :email, "Email:" %>
        <%= form.text_field :email, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline' %>
      </div>
      <div class="mb-2">
        <%= form.label :width, "Board Width:" %>
        <%= form.number_field :width, in: 1...-1, step: 1, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline' %>
      </div>
      <div class="mb-2">
        <%= form.label :height, "Board Height:" %>
        <%= form.number_field :height, in: 1...-1, step: 1, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline' %>
      </div>
      <div class="mb-2">
        <%= form.label :name, "Board Name:" %>
        <%= form.text_field :name, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline' %>
      </div>
      <div class="mb-6">
        <%= form.label :mines, "Number of mines:" %>
        <%= form.number_field :mines, in: 1...-1, step: 1, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline' %>
      </div>
      <%= form.submit "Generate Board", class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline' %>
    </div>
  <% end %>

  <!--  Last 10 games -->
  <div class="flex flex-col gap-y-1 bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
    <h2 class="mb-2"><strong>Last 10 games</strong></h2>

    <%= render "shared/table", games: @games %>

    <%= link_to 'View all generated boards', games_path, class: 'underline' %>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <main class="w-full px-5 py-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_board.html.erb
<div class="flex flex-col gap-y-1">
  <% board.each { |row| %>
    <div class="flex gap-x-1">
      <% row.each { |element| %>
        <% if element == 1%>
          <%= image_tag 'bomb.svg', size: '20x20', alt: 'bomb-icon' %>
        <% else %>
          <div class="rounded-lg bg-gray-100" style="width: 20px; height: 20px;"></div>
        <% end %>
      <% } %>
    </div>
  <% } %>
</div>

app/views/shared/_table.html.erb
<table class="border-spacing-2">
  <thead>
  <tr>
    <th>Item</th>
    <th></th>
    <th>Board Name</th>
    <th>User Email</th>
    <th>Created At</th>
  </tr>
  </thead>
  <tbody>
  <% @games.each_with_index do |game, index| %>
    <tr>
      <td class="p-1">
        <%= index + 1 %>
      </td>
      <td class="p-2"></td>
      <td class="p-1">
        <%= link_to game.name, game, class: 'underline' %>
      </td>
      <td class="p-1">
        <%= game.email %>
      </td>
      <td class="p-1">
        <%= local_time(game.created_at, :long) %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>